#
# Copyright 2025 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Trivy Scan

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - docker-rebuild
      - release-please
    types:
      - completed
    branches:
      - main

  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  image-tags:
    if: >-
      github.repository_owner == 'OKDP' &&
      (
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'schedule' ||
        github.event.workflow_run.conclusion == 'success'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      image_tags: ${{ steps.trivy-versions.outputs.image_tags }}

    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Get Trivy image matrix
        id: trivy-versions
        uses: ./.github/actions/trivy-versions
        with:
          registry: ${{ vars.REGISTRY || 'quay.io' }}
          repository_owner: ${{ github.repository_owner }}

  trivy-scan:
    needs: [image-tags]
    if: github.repository_owner == 'OKDP'
    permissions:
      contents: read
      security-events: write
      actions: read

    name: Scan ${{ matrix.image_tag }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.image-tags.outputs.image_tags) }}

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8 # v0.36.0
        with:
          image-ref: ${{ matrix.image }}
          format: sarif
          output: trivy-results-${{ matrix.image_tag }}.sarif
          severity: CRITICAL,HIGH

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@1a818fd5f97ed0ee9a823421bd5b171add01227f # v4.36.2
        with:
          sarif_file: trivy-results-${{ matrix.image_tag }}.sarif
          category: trivy-hive-metastore-${{ matrix.image_tag }}
